/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as wethSol from "./WETH.sol";
export type { wethSol };
export type { MockERC20 } from "./MockERC20";
